### ndarray 정렬 

In [2]:
import numpy as np

##### 1차원 배열 정렬

In [3]:
arr = np.random.randint(1, 11, 10)
arr

array([ 3,  7, 10,  8,  2,  2,  6,  1,  2,  3], dtype=int32)

In [4]:
# np.sort(arr) : 정렬된 ndarray를 반환. 변수에 덮어씌워줘야 한다.
# np.sort(arr)[::-1] : 역순으로 정렬
print(np.sort(arr))
arr = np.sort(arr)
print(arr)

[ 1  2  2  2  3  3  6  7  8 10]
[ 1  2  2  2  3  3  6  7  8 10]


---

##### 2차원 배열 정렬

In [5]:
arr = np.random.randint(10, size=(3, 4))   # 시작값을 생략하면 0 이상. 즉, 0 이상 10 미만의 (3, 4). 이 경우 size= 를 생략하면 에러가 난다
                                           # 시작값, 끝값을 위치 인자로 받기 때문에 size= (키워드인자)를 생략하면 에러.
arr

array([[3, 9, 2, 2],
       [3, 5, 0, 2],
       [9, 3, 4, 1]], dtype=int32)

In [6]:
np.sort(arr)   # 기본값 axis=1 열방향 정렬

array([[2, 2, 3, 9],
       [0, 2, 3, 5],
       [1, 3, 4, 9]], dtype=int32)

In [7]:
print(np.sort(arr, axis=0))   # 행방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1))   # 열방향 정렬 (같은 행 안에서 정렬) <- 기본값.

[[3 3 0 1]
 [3 5 2 2]
 [9 9 4 2]]
[[2 2 3 9]
 [0 2 3 5]
 [1 3 4 9]]


In [8]:
print(np.sort(arr, axis=None))  # axis=None의 경우 축 무시. (행/열 구분없이 모든 값 정렬)
                                # 1차원 배열로 정렬이 된다. (축이 사라진다. 즉, 차원을 없앤다)
print(np.sort(arr, axis=None).shape)

[0 1 2 2 2 3 3 3 4 5 9 9]
(12,)


##### np.argsort
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [9]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr)) # 정렬된 배열의 각 요소의 원래 자리의 인덱스를 반환해준다.

[100 200 300 400]
[0 2 3 1]


In [10]:
names = np.array(['리사', '로제', '제니', '지수'])
album_sales = np.array([900, 870, 1000, 670])

print(np.sort(album_sales)[::-1])
sales_desc = np.argsort(album_sales)[::-1]
print(sales_desc)
names[sales_desc]

# 내가 푼 방법
# print(np.sort(album_sales)[::-1])
# indices = np.argsort(album_sales)[::-1]

# print(names[indices])

[1000  900  870  670]
[2 0 1 3]


array(['제니', '리사', '로제', '지수'], dtype='<U2')

In [11]:
# 2차원 배열에서 argsort

arr = np.array([[2025, 2, 28], [17, 18, 30]])
print(arr)
print("=================")
print(np.sort(arr))
print(np.argsort(arr))
print(np.argsort(arr, axis=1)) # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print("=================")
print(np.sort(arr, axis=0))
print(np.argsort(arr, axis=0)) # 행 방향 정렬의 순서 (같은 열 안에서 정렬)

[[2025    2   28]
 [  17   18   30]]
[[   2   28 2025]
 [  17   18   30]]
[[1 2 0]
 [0 1 2]]
[[1 2 0]
 [0 1 2]]
[[  17    2   28]
 [2025   18   30]]
[[1 0 0]
 [0 1 1]]
