다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [2]:
import numpy as np

In [15]:
arr_a = np.array([200, 340, 150, 400])
arr_b = np.array([220, 300, 180, 420])
print(arr_a)
print(arr_b)
print("1분기와 2분기의 과일별 총 판매량: ", arr_a + arr_b)
print("1분기와 2분기의 과일별 평균 판매량: ", (arr_a + arr_b) / 2)
print("1분기와 2분기의 과일별 평균 판매량: ", np.average([arr_a, arr_b], axis=0))

[200 340 150 400]
[220 300 180 420]
1분기와 2분기의 과일별 총 판매량:  [420 640 330 820]
1분기와 2분기의 과일별 평균 판매량:  [210. 320. 165. 410.]
1분기와 2분기의 과일별 평균 판매량:  [210. 320. 165. 410.]


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [3]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print("덧셈")
print(arr1 + arr2)
print(np.add(arr1, arr2))
print("==============")
print("뺄셈")
print(arr1 - arr2)
print(np.subtract(arr1, arr2))
print("==============")
print("곱셈")
print(arr1 * arr2)
print(np.multiply(arr1, arr2))
print("==============")
print("나눗셈")
print(arr1 / arr2)
print(np.divide(arr1, arr2))

덧셈
[11 22 33 44]
[11 22 33 44]
뺄셈
[ 9 18 27 36]
[ 9 18 27 36]
곱셈
[ 10  40  90 160]
[ 10  40  90 160]
나눗셈
[10. 10. 10. 10.]
[10. 10. 10. 10.]


다음 두 배열 간의 내적 연산을 수행하세요.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 @ arr2)

32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

In [7]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]
